pointwest/S15-S16/FinalTestChar/FinalTestChar/Models/Course.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FinalTestChar.Models
{
    public class Course
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [Column(TypeName = "decimal(6,2)")]
        public decimal Price { get; set; }

        [Display(Name = "Unit")]
        public int Quantity { get; set; } = 1;

        [Required]
        [DataType(DataType.ImageUrl)]
        public string Logo { get; set; }
    }
}

pointwest/S15-S16/FinalTestChar/FinalTestChar/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using FinalTestChar.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Text.Json;
using Newtonsoft.Json.Linq;
using System.Xml.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace FinalTestChar.Controllers
{
    public class CourseController : Controller
    {
        private readonly LaZuittContext _context;
        public bool isStudentAdded = false;

        public CourseController(LaZuittContext context)
        {
            _context = context;
        }

        public int[] idList = { };
        private int[] fromPostId = { };

        public int[] pubDummy = { 2, 1, 3 };

        // Retreive and display Courses on the Index page
        public async Task<IActionResult> Index()
        {
            //TempData["count"] = idList.Count();
            TempData.Keep();

            return View(await _context.Course.ToListAsync());

        }

        // Retrieve course by Id
        public ActionResult AddToCart(int id)
        {
            var query = _context.Course.Where(i => i.Id == id).FirstOrDefault();
            return View(query);
        }

        // Redirect to Course/Index.cshtml after clicking Add To Cart button

        [HttpPost]
        public ActionResult AddToCart()
        {
            return RedirectToAction("Index");
        }

        // Display items at the checkout page based on Id's save in the local storage

        public ActionResult EmptyCart()
        {
            return View();
        }

        public ActionResult Checkout()
        {
            return View();
        }


        [HttpGet]
        [Route("[controller]/CheckoutCart")]
        //[ActionName("Checkout")]
        public ActionResult _MyCart(string values, bool btnClicked)
        {
            //Console.WriteLine("this is from get result: " + JsonConvert.SerializeObject(values)); // "1, 2, 3"

            Console.WriteLine("bool" + btnClicked);

            if (btnClicked == true)
            {
                Console.WriteLine("im clicked");

                //var tblEnroll = from e in _context.Enroll select e;

                //foreach(var item in tblEnroll.ToList())
                //{
                //    Enroll enroll = new Enroll
                //    {
                //        StudentId = 1,
                //        CourseId = 3,
                //        EnrollDate = DateTime.Today,
                //        BillingAddress = "lorem"
                //    };

                //    Console.WriteLine("dotpppp");

                //    _context.Enroll.Add(enroll);
                    
                //};
                    
                //return View();
            }

            else
            {
                Console.WriteLine("Not clicked");
            }

            int[] dummyValues = { 2, 3, 1 };

            string value = String.Join(", ", values);
            string newValue = new string(value); // 1, 2, 3

            int[] ids = newValue.Select(i => i - '0').ToArray(); // string to int[]


            //Console.WriteLine("converted: " + newValue);


            var course = _context.Course.Where(x => ids.Contains(x.Id)).ToList();
            //return View(course);

            var res = JsonConvert.SerializeObject(course);
            //Console.WriteLine(res);
            var param = new { cart = course };

            return Json(res);
        }



        //Student Entry
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Route("[controller]/Checkout")]
        public async Task<IActionResult> Checkout([Bind("Id,FirstName,LastName,Email")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        [HttpPost]
        [Route("[controller]/ButtonClick")]
        public ActionResult ButtonClick(string button, bool clicked)
        {
            bool isClick = false;
            if (button == "Checkout")
            {
                isClick = true;
                var tblEnroll = from c in _context.Course select c;

                Enroll enroll = new Enroll
                {
                    StudentId = 1,
                    CourseId = 2,
                    EnrollDate = DateTime.Today,
                    BillingAddress = "lorem"
                };

                //Enroll enroll = new Enroll();
                //enroll.StudentId = 1;
                //enroll.CourseId = 2;
                //enroll.EnrollDate = DateTime.Now;
                //enroll.BillingAddress = "lorem";


                Console.WriteLine("dotpppp");

                //_context.Add(enroll);
                _context.Add(enroll);
                _context.SaveChanges();




            }
            return RedirectToAction("_MyCart", new { btnClicked = isClick });
        }
    }
}

pointwest/S15-S16/FinalTestChar/FinalTestChar/Views/Course/AddToCart.cshtml
@model FinalTestChar.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />

@using (Html.BeginForm())
{
    <input type="hidden" name="id" id="id" value="@Model.Id" />
    <dl class="row">
        <dt class="col-sm-2">
            Title
        </dt>
        <dd class="col-sm-10">
            @Model.Title
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Model.Description
        </dd>
        <dt class="col-sm-2">
            Price
        </dt>
        <dd class="col-sm-10">
            @Model.Price
        </dd>
        <dt class="col-sm-2">
            Quantity
        </dt>
        <dd class="col-sm-10">
            @Model.Quantity
        </dd>
        <dt class="col-sm-2">
            Logo
        </dt>
        <dd class="col-sm-10">
            @Model.Logo
        </dd>
    </dl>

    <input type="submit" value="Add To Cart" class="btn btn-primary" onclick="saveData()" />
}

<script>
    function saveData() {

        let idList = localStorage.getItem('Id'), array = [];
        let entryId = document.getElementById("id").value;
        const courseId = [1, 2, 3, 4];


        if (!idList) {
            idList = localStorage.setItem("Id", document.getElementById("id").value);
        }

        array = idList.split(',');


        if (!idList.includes(courseId)) {

            if (idList.includes(entryId)) {
                return alert("Item already exists");
            }

            else
            {
                array.push(document.getElementById('id').value);
                idList = array.join(',');
                localStorage.setItem('Id', idList);
            }
        }
    }
</script>

<div>
    <a asp-action="Index">Back to List</a> |
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

pointwest/S15-S16/FinalTestChar/FinalTestChar/Views/Course/Checkout.cshtml
@model FinalTestChar.Models.Course

@{

    ViewData["Title"] = "Checkout";

    <style>
        .logo {
            display: block;
            margin: 0 auto;
            width: 50px;
            height: 50px;
        }

        .text-center {
            text-align: center;
        }

        .text-right {
            text-align: right;
        }

        .borderless th, .borderless td {
            border: none;
        }

        .customer-info,
        #is-shown {
            display: flex;
            justify-content: flex-end;
            visibility: hidden;
        }

        #totalAmount {
            font-weight: bold;
        }
    </style>

}

<partial name="_MyCart" />


<script>
    function saveRecord() {
        @*$.ajax({
            type: 'POST',
            url: 'http://localhost:38310/Course/Checkout',
            data:
            success: function (data) {
                return data;
            }
        });*@

        let ids = JSON.stringify(localStorage.getItem("Id"));
        ids = JSON.parse(ids);
        let values = { values: ids };

        console.log(ids);

        $.ajax({
            type: 'POST',
            url: 'http://localhost:38310/Course/ButtonClick',
            traditional: true,
            data: values,
            dataType: "json",
            success: function (data) {
                console.log(data + "succ");

            },
            error: function (err) {
                console.log("err");
            }
        });
    }
</script>

<hr style=" height: 2px" />

<div class="row customer-info" id="is-shown">

    <div class="col-md-6">
        <h4 class="pb-2 text-right">Customer Information</h4><br />
        <form asp-action="Checkout">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display: flex;">
                <input name="FirstName" class="form-control" type="text" placeholder="First name" style="margin-right: 8px" required />
                <input name="LastName" class="form-control" type="text" placeholder="Last name" style="margin-left: 8px;" required />
            </div>

            <div class="form-group">
                <input name="Email" class="form-control" type="email" placeholder="Email" required />
            </div>

            <div class="form-group">
                <input name="BillingAddress" class="form-control" type="text" placeholder="Billing Address" required />
            </div>

            <div>
            </div>

            @*<div class="form-group text-right">
                <button type="submit" name="button" value="Checkout" class="btn btn-primary" asp-controller="Course" asp-action="_MyCart" onclick="nones()">Checkout</button>
            </div>*@
            <div class="form-group text-right">
                <input type="submit" name="button" value="Checkout" class="btn btn-primary" asp-action="ButtonClick" onclick="saveRecord()"/>
                 @*<input type="submit" name="button" value="Checkout" class="btn btn-primary" asp-action="" onclick="saveRecord();"  style="display: none;" />*@
            </div>
        </form>
    </div>
</div>

pointwest/S15-S16/FinalTestChar/FinalTestChar/Views/Course/EmptyCart.cshtml
@{
    ViewData["Title"] = "Empty Cart";
}

<h2 class="text-danger text-center">Your Cart is Empty.</h2>
<p class="text-center">@Html.ActionLink("Check Available Courses", "Index", "Course")</p>

pointwest/S15-S16/FinalTestChar/FinalTestChar/Views/Course/Index.cshtml
@model IEnumerable<FinalTestChar.Models.Course>
@{
    ViewData["Title"] = "Enroll Course";
}
    
<style>

    .logo {
        display: block;
        margin: 0 auto;
        width: 150px;
        height: 150px;
    }

    .spacing {
        padding-top: 10px;
    }

    .column {
        float: left;
        width: 25%;
        padding: 0 10px;
        max-height: 100%;
    }

    .card-header, .card-footer {
        background-color: #fff;
    }

    .btn {
        margin-top: 10px;
        margin-bottom: 10px;
        width: 100%;
    }
</style>


<h1 class="pb-4">Enroll Now!</h1>

<div class="row pb-4">
    @foreach (var item in Model)
    {
        <div class="column">
            <div class="card h-100">
                <div class="card-header">
                    @if (item.Logo != null)
                    {
                        <img src="@Url.Content(item.Logo)" class="logo" alt="Logo" />
                    }
                </div>
                <div class="card-body">
                    <h5 class="card-title spacing">@Html.DisplayFor(modelItem => item.Title)</h5>
                    <p class="card-text">@Html.DisplayFor(model => item.Description)</p>
                    <p class="card-text">&#8369;@Html.DisplayFor(model => item.Price)</p>
                </div>
                <div class="card-footer">
                    <a asp-action="AddToCart" asp-route-id="@item.Id">Enroll</a>
                </div>
            </div>
        </div>
    }
</div>